job: 
  - name: one
    host: ['192.168.0.1:22', '192.168.0.2:22']
    user: root
    password: 'admin12345'
    parallelNum: 5
    srcFile: ./playbook.yml
    destDir: /data/test
    cmd: pwd;ls
    shell: |
      echo "hello world 111111"
      cat > test.txt <<EOF
      hello world
      my host is here
      EOF
db:
  - name: mysql
    host: 192.168.223.5
    port: 3306
    dbtype: mysql
    username: root
    password: 'admin12345'
    database: test
  - name: postgresql
    host: 192.168.223.5
    port: 5432
    dbtype: postgresql
    username: postgres
    password: 'admin12345'
    database: test
  - name: redis
    host: 192.168.223.5
    port: 6379
    dbtype: redis
    username: 'root'
    password: 'admin12345'
    database: 0