project_name: adp
#before:
  #hooks:
    # You may remove this if you don't use go modules.
    #- go mod tidy
builds:
  - goos: # 编译平台列表 
      - linux
      - windows
      - darwin
    goarch: [amd64, arm64]
#checksum:
#  name_template: 'checksums.txt'
archives:
  #- replacements:
  #    linux: Linux
  #    windows: Windows
  #    darwin: MacOs
  #    386: i386
  #    amd64: x86_64
  - format_overrides:
      - goos: windows
        format: zip
    files: # 添加到压缩包内的文件列表
      - README.md