name: Build Release
 
on:
  push:
    # Pattern matched against refs/tags
    tags:      
      - '*'           # 创建所有 tag 都运行打包 v* 则 v1.0 这种也行
 
jobs:
 
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
 
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.20
        cache: true
        go-version-file: 'go.mod'
        cache-dependency-path: 'go.sum'
    - name: Build
      run: go build -v .
 
      # 使用 goreleaser 进行生成多平台代码并且上传到 github release 进行发布
    - name: Create release on GitHub
      uses: docker://goreleaser/goreleaser:latest
      with:
        args: release
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}